# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_site.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('license_no', models.CharField(max_length=50, unique=True)),
                ('license_validity', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('picture', models.ImageField(default='default.png', upload_to=main_site.models.get_upload_path)),
            ],
            options={
                'ordering': ['license_validity'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_at', models.DateTimeField()),
                ('date_of_journey', models.DateField()),
                ('time_of_journey', models.TimeField()),
                ('no_of_persons_travelling', models.IntegerField(default=1)),
                ('description', models.TextField(null=True)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('is_return_journey', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_of_journey'],
            },
        ),
        migrations.CreateModel(
            name='TripStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=15)),
                ('description', models.TextField(null=True)),
                ('fuel_capacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('expected_cost', models.FloatField()),
                ('actual_cost', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Vehicle')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('start_distance_reading', models.FloatField(blank=True, null=True)),
                ('end_distance_reading', models.FloatField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_site.TransportRequest')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.VehicleStatus'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.VehicleType'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.RequestType'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.RequestStatus'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('datetime_of_generation', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_site.Trip')),
                ('total_distance', models.FloatField()),
                ('discount_percentage', models.FloatField(default=0)),
                ('total_fare', models.FloatField()),
            ],
            options={
                'ordering': ['datetime_of_generation'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='drivers',
            field=models.ManyToManyField(to='main_site.Driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.TripStatus'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicles',
            field=models.ManyToManyField(to='main_site.Vehicle'),
        ),
    ]
