# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
