# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 17:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20171114_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.Status'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='blood_group',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('NA', 'NA')], max_length=2, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='picture',
            field=models.ImageField(default='driver-default.png', help_text='If not provided, default will be used', upload_to=main_site.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='repairing_cost',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate/km'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(default='schoolbus-default.png', help_text='If not provided, default will be taken', upload_to=main_site.models.get_upload_path),
        ),
    ]
