# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20171029_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportrequest',
            options={'ordering': ['date_of_journey']},
        ),
    ]
