# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20171029_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.TripStatus'),
        ),
    ]
