# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_auto_20171029_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='preferred_vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.VehicleType'),
        ),
    ]
