# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_transportrequest_preferred_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='rate',
        ),
        migrations.AddField(
            model_name='requesttype',
            name='rate',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
