# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_auto_20171029_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_generation', models.DateTimeField(default=datetime.datetime(2017, 10, 30, 6, 59, 2, 240622, tzinfo=utc))),
                ('total_distance', models.FloatField()),
                ('discount_percentage', models.FloatField(default=0)),
                ('total_fare', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='end_distance_reading',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_distance_reading',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Trip'),
        ),
    ]
