# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_auto_20171030_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='datetime_of_generation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
