# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main_site.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_auto_20171030_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('expected_cost', models.FloatField()),
                ('actual_cost', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Vehicle')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['datetime_of_generation']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['license_validity']},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transportrequest',
            name='preferred_vehicle_type',
        ),
        migrations.RemoveField(
            model_name='transportrequest',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='driver',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=main_site.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='no_of_persons_travelling',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.RequestStatus'),
        ),
        migrations.AddField(
            model_name='trip',
            name='drivers',
            field=models.ManyToManyField(to='main_site.Driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicles',
            field=models.ManyToManyField(to='main_site.Vehicle'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_site.Trip'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_validity',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_distance_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_site.TransportRequest'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_distance_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.VehicleStatus'),
        ),
    ]
